### ISSUE TITLE
Problems with SHA256

### ISSUE THREAD

**Issue by giriarteS** [nextgenusfs/homebrew-tap#1]
I have been trying to install ufits but I get the following:
`==> Installing ufits from nextgenusfs/tap`
`==> Downloading https://github.com/nextgenusfs/ufits/archive/0.7.4.tar.gz`
`######################################################################## 100.0%`
`Error: SHA256 mismatch`
`Expected: 4ac5de85ea06dd6a7eb3ffb1e533b897b9501add9891990f95960ed0b9a67699`
`Actual: 8dcd547e6e6619c360467bb8731b2a1046b297f25fb44f2b0cd11f0415b692d2`
`Archive: /Users/BrodersLab/Library/Caches/Homebrew/ufits-0.7.4.tar.gz`
`To retry an incomplete download, remove the file above.`

The same with braker:
`==> Installing braker from nextgenusfs/tap`
`==> Downloading http://bioinf.uni-greifswald.de/augustus/binaries/BRAKER2.tar.gz`
`######################################################################## 100.0%`
`Error: SHA256 mismatch`
`Expected: e2097a9cfa9c44fe09cfc1d9c1e57605a29480a91c564aa932e0555bd57c78ab`
`Actual: 805e9c7354816380ee7afe716c7e5913c1f92e950ff1586a919ac8b540f8577d`
`Archive: /Users/BrodersLab/Library/Caches/Homebrew/braker-2.0.2.tar.gz`

**Comment by nextgenusfs** [comment]
This tool (ufits) has been renamed amptk -- see here: http://amptk.readthedocs.io/en/latest/.   I'm no longer maintaining this BRAKER tap as they keep changing the location of the files.

**Comment by nextgenusfs** [comment]
old formulas removed
