### ISSUE TITLE
evidencemodeler error

### ISSUE THREAD

**Issue by giriarteS** [nextgenusfs/homebrew-tap#2]
evidencemodeler fails:
`brew info evidencemodeler`
`nextgenusfs/tap/evidencemodeler: stable 0.1.3`
`EVidenceModeler combines gene prediction/evidence into weighted gene predictions`
`http://evidencemodeler.github.io`
`/usr/local/Cellar/evidencemodeler/0.1.3 (89 files, 13.7MB) *`
`  Built from source on 2018-05-31 at 10:55:49`
`From: https://github.com/nextgenusfs/homebrew-tap/blob/master/evidencemodeler.rb`
`Error: Calling <<-EOS.undent is disabled!`
`Use <<~EOS instead.`
`/usr/local/Homebrew/Library/Taps/nextgenusfs/homebrew-tap/evidencemodeler.rb:17:in ``caveats'`
`Please report this to the nextgenusfs/tap tap!`
`Or, even better, submit a PR to fix it!`

**Comment by nextgenusfs** [comment]
The install didn't fail, just giving an error about a new format. evidence modeler formula updated, should work now.
